### ISSUE TITLE
(v0.4.1) Error: Cannot find module '/app/dist/src/server.js'

### ISSUE THREAD

**Issue by zackslash** [Nikorag/iplayarr#72]
Hi,
After upgrading docker version of iplayarr to v0.4.1 the container immediately exists on start with the error ' Cannot find module '.
This is running with the internal Redis and using the same configuration from the previous builds.

```
Node.js v23.11.0
Starting redis
Starting container with UID:1027 and GID:100
7:C 02 Apr 2025 16:48:13.393 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
7:C 02 Apr 2025 16:48:13.393 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
7:C 02 Apr 2025 16:48:13.393 * Redis version=7.4.2, bits=64, commit=00000000, modified=0, pid=7, just started
7:C 02 Apr 2025 16:48:13.393 # Warning: no config file specified, using the default config. In order to specify a config file use /redis/redis-server /path/to/redis.conf
7:M 02 Apr 2025 16:48:13.393 * monotonic clock: POSIX clock_gettime
7:M 02 Apr 2025 16:48:13.394 * Running mode=standalone, port=6379.
7:M 02 Apr 2025 16:48:13.394 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
7:M 02 Apr 2025 16:48:13.395 * Server initialized
7:M 02 Apr 2025 16:48:13.395 * Ready to accept connections tcp
> iplayarr@1.0.0 start
> node dist/src/server.js
node:internal/modules/cjs/loader:1408

  throw err;
  ^
Error: Cannot find module '/app/dist/src/server.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1405:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1061:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1066:22)
    at Function._load (node:internal/modules/cjs/loader:1215:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:151:5)
    at node:internal/main/run_main_module:33:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by Nikorag** [comment]
🤦 sorry - This is an obvious mistake by me not testing the compile and start. Once i removed the tests (because there was only one) it's no longer compiling the src directory under dist. It's just dist.

will roll a fix out ASAP

**Comment by zackslash** [comment]
Can confirm this is now working in 0.4.2, thank you!
